config/routes.rb
Rails.application.routes.draw do
  resource :users, only: [:create, :new, :show]
  resource :session, only:[:create, :new, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
validates :email, :password_digest, :session_token, presence: true
validates :email, :session_token, uniqueness: true
validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

after_initialize :ensure_session_token

attr_reader :password

def self.find_by_credentials(email, password)
  user = self.find_by(email: email)
  return nil if user.nil?
  user.is_password?(password) ? user : nil
end

def self.generate_session_token
  token = SecureRandom::urlsafe_base64(16)
  while User.exists?(session_token: token)  # ActiveRecord method
    token = SecureRandom::urlsafe_base64(16)
  end
  token
end

def reset_session_token!
  self.session_token = User.generate_session_token
  self.save
end

def ensure_session_token
  self.session_token ||= User.generate_session_token
end

# will be saved in controller
def password=(password)
  @password = password
  self.password_digest = BCrypt::Password.create(password)
end

def is_password?(password)
   BCrypt::Password.new(password_digest).is_password?(password)
end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  # fetches the user we've logged in as
  def current_user
    # @current_user ||=
     User.find_by(session_token: session[:session_token])
  end

  # set session[session_token] signs them in
  def log_in_user!(user)
    session[:session_token] = user.session_token.reset_session_token!
  end

  def log_out_user
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    session[:session_token] == current_user.session_token
  end
end

# controllers will always have the params and session hash available to them
# session hash - a form of an encrypted cookie

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # signs a user in
  def create
    em = params[:user][:email]
    pw = params[:user][:password]

    @user = User.find_by_credentials(em, pw)
      if @user && @user.is_password?(pw)
        log_in_user!(user)
        redirect_to users_url
      else
        flash.now[:errors] = "Wrong username or password"
        @user = User.new(email: em)
        render :new
      end
  end

# presents log in form
  def new
    @user = User.new
    render :new
  end

# sign a user out
  def destroy
    log_out_user
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#get /users/new return an HTML form to create a new User
  def new
    @user = User.new
    render :new
  end

# post /users add a user object to users
  def create
    @user = User.new(user_params)
    if @user.save
        log_in_user!(@user)
        redirect_to users_url
    else
      render :new
    end
  end

  # get /users display a specific user
  def show
    @user = current_user
    render :show
  end

private

  # where does this come from? scope includes view.
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

# edit is like new
# update is like create

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
  <%= button_to "Logout", session_url, method:delete %>
  <% end
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.email.capitalize %></li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up for our awesome Music App!</h1>

<ul>
  <% @user.errors.full_messages.each do |err| %>
    <li><%= err %></li>
    <% end %>
</ul>

<form action="<%= users_url %>" method="post">
  <input  type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">

<label>Username
<input type="text" name="user[email]" value="<%= @user.email %>">
</label>
<br>

<label>Password
<input type="password" name="user[password]">
</label>
<br>

<input type="submit" value="Sign me up!">
</form>

app/views/users/show.html.erb
<h1>Welcome <%= @user.email %>!<h1>

<form action="<%= session_url %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <input type="submit" value="Log out!">
</form>